[package]
name = "day06b"
version = "0.1.0"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
edition = "2021"

[lib]
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
